### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nido975** [tjhwangxiong/TCGAplot#1]
when i use "devtools::install_local("TCGAplot_4.0.0.zip") "
 to install TCGAplot
i got those error information:
* installing *binary* package 'TCGAplot' ...
cp: unknown option -- )
Try '/c/RBUILD~1/4.3/usr/bin/cp --help' for more information.
ERROR: installing binary package failed
* removing 'C:/Users/monkey/AppData/Local/R/win-library/4.3/TCGAplot'

R in 4.3.2, windows environment

**Comment by tjhwangxiong** [comment]
Please download the package from: [https://github.com/tjhwangxiong/TCGAplot/releases/download/v4.0.0/TCGAplot_4.0.0.zip](https://github.com/tjhwangxiong/TCGAplot/releases/download/v4.0.0/TCGAplot_4.0.0.zip) or [https://pan.baidu.com/s/1I81yfkJbJAg5ZNRyUsOxPw?pwd=wd5j](https://pan.baidu.com/s/1I81yfkJbJAg5ZNRyUsOxPw?pwd=wd5j)
Then, install the package locally.

DO NOT USE devtools to install.
