### ISSUE TITLE
not available for Bioconductor version '3.18'

### ISSUE THREAD

**Issue by Zaidsk70** [tjhwangxiong/TCGAplot#11]
```
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install()
BiocManager::install("TCGAplot")

```
**Output in console pane**
Warning message:
package ‘TCGAplot’ is not available for Bioconductor version '3.18'

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by tjhwangxiong** [comment]
https://github.com/tjhwangxiong/TCGAplot/releases/download/v8.0.0/TCGAplot_8.0.0.zip

Please download the latest TCGAplot v8.0.0
