### ISSUE TITLE
gene_TMB_radar

### ISSUE THREAD

**Issue by AMAwatermelon** [tjhwangxiong/TCGAplot#12]
在gene_TMB_radar的源码中 method被指定为’Pearson‘，使得传递的参数无效

**Comment by tjhwangxiong** [comment]
![image](https://github.com/tjhwangxiong/TCGAplot/assets/94770704/741eb241-a39d-4b83-952c-daa9a4a39041)
gene_TMB_radar("KLF7",method = "pearson")

"pearson" not "Person"

**Comment by AMAwatermelon** [comment]
我的意思是method被指定为了"pearson"，即使函数中输入method=‘spearman’，返回的仍然是pearson结果

**Comment by tjhwangxiong** [comment]
Thanks for your report. We have revised this bug in Version 7.0.1.

Please download TCGAplot_v7.0.1 at https://github.com/tjhwangxiong/TCGAplot/releases/download/v7.0.1/TCGAplot_7.0.1.zip
