### ISSUE TITLE
the ticks of radar chart are not equal interval

### ISSUE THREAD

**Issue by srplot** [tjhwangxiong/TCGAplot#13]
as shown in the radar chart, the ticks are not equally distributed.
![gene_TMB_radar](https://github.com/tjhwangxiong/TCGAplot/assets/166795676/94c91d31-6d41-4d0b-9a2d-fdf4435183c6)
ticks interveal from 0.1, 0.2, 0.2, to 0.1 (from outer to inner). maybe all 0.1 is better.

**Comment by tjhwangxiong** [comment]
caxislabels = c(round(res["Min",1],1),
                             round(res["Min",1]+0.25*(res["Max",1]-res["Min",1]),1),
                             round(res["Min",1]+0.5*(res["Max",1]-res["Min",1]),1),
                             round(res["Min",1]+0.75*(res["Max",1]-res["Min",1]),1),
                             round(res["Max",1],1)))
