### ISSUE TITLE
KMplot criteria

### ISSUE THREAD

**Issue by TakatoG** [tjhwangxiong/TCGAplot#17]
Hi.
What are the criteria for high and low expression in KMplot?
(based on average expression?)
Thank you.

**Comment by tjhwangxiong** [comment]
median value

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："T. ***@***.***&gt;;
发送时间：2024年7月1日(星期一) 晚上6:47
收件人："tjhwangxiong/TCGAplot" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[tjhwangxiong/TCGAplot] KMplot criteria (Issue #17)
-----------------------------------

 

 
Hi.
 What are the criteria for high and low expression in KMplot?
 (based on average expression?)
 Thank you.

**Comment by TakatoG** [comment]
Thank you so much!
