### ISSUE TITLE
When tpm values are all zeros,  the gene_TMB_radar function not working

### ISSUE THREAD

**Issue by microbioin** [tjhwangxiong/TCGAplot#20]
For this UGT1A9 gene, the tpm values in UVM cancer type is all 0. so the correlation calculation in gene_TMB_radar function will show "the standard deviation is zero" , and the radar chart will be broken. Hope to add a checking function. Thank you.

**Comment by tjhwangxiong** [comment]
可能是因为我们为了让R包整体大小小一点，tpm我们只保留了一位小数。








 Department of Laboratory Medicine, Tongji Hospital,
Tongji Medical College, Huazhong University of Science and Technology,
Wuhan, 430030, China
Tel: +86 027-83665471
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; +86 13554663391
 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Sep 19, 2024 10:54 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[tjhwangxiong/TCGAplot] When tpm values are all zeros,  the gene_TMB_radar function not working (Issue #20)

&nbsp;



 
For this UGT1A9 gene, the tpm values in UVM cancer type is all 0. so the correlation calculation in gene_TMB_radar function will show "the standard deviation is zero" , and the radar chart will be broken. Hope to add a checking function. Thank you.

**Comment by microbioin** [comment]
this may be the reason. I extract the tpm of all genes for all samples, about 1G. so huge. thank you,
