### ISSUE TITLE
object 'tpm' not found

### ISSUE THREAD

**Issue by korjcjeong** [tjhwangxiong/TCGAplot#3]
It appears that there is a missing data file or a function to load 'tpm.' 
The current code is not functioning as expected as shown below. 

> get_tpm("COAD")
Error in get_tpm("COAD") : object 'tpm' not found

> pan_boxplot("KLF7")
Error in pan_boxplot("KLF7") : object 'tpm' not found

FYI, 

Based on your codes below:
setwd("./rawdata/methy/")
load("../tpm.Rdata")
library(TCGAbiolinks)
methy=methy[rownames(methy) %in% rownames(tpm),]

There was 'tpm.Rdata', but it doesn't exist in this distribution. 

Thanks.

**Comment by tjhwangxiong** [comment]
It seems the TCGAplot R package was not sucessfully installed.
To install this package, download TCGAplot R package at https://github.com/tjhwangxiong/TCGAplot/releases/download/v5.0.0/TCGAplot_5.0.0.zip
DO NOT INSTALL USING "devtools", PLEASE download the .zip file and install the package locally.

Moreover, there were several dependent R packages for TCGAplot, and you could install these R packages using the following codes.
```
options("repos"="https://mirrors.ustc.edu.cn/CRAN/")
if(!require("BiocManager")) install.packages("BiocManager",update = F,ask = F)
options(BioC_mirror="https://mirrors.ustc.edu.cn/bioc/")

cran_packages=c("magrittr",
                "dplyr",
                "tibble",
                "ggpubr",
                "stringr",
                "reshape2",
                "psych",
                "limma",
                "circlize",
                "grid",
                "fmsb",
                "survival",
                "survminer",
                "forestplot",
                "pROC",
                "tinyarray",
                "ggplot2",
                "patchwork",
                "ggsci",
                "RColorBrewer",
                "pheatmap")

Biocductor_packages=c("edgeR",
                      "org.Hs.eg.db",
                      "clusterProfiler",
                      "enrichplot",
                      "ComplexHeatmap",
                      "GSVA")

# install packages in CRAN
for (pkg in cran_packages){
  if (!require(pkg,character.only=T)){
    install.packages(pkg,ask = F,update = F)
    require(pkg,character.only=T) 
  }
}

# install packages in Biocductor
for (pkg in Biocductor_packages){
  if (!require(pkg,character.only=T)) {
    BiocManager::install(pkg,ask = F,update = F)
    require(pkg,character.only=T) 
  }
}
```


> Based on your codes below:
setwd("./rawdata/methy/")
load("../tpm.Rdata")
library(TCGAbiolinks)
methy=methy[rownames(methy) %in% rownames(tpm),]
There was 'tpm.Rdata', but it doesn't exist in this distribution.

These codes were used to build the rawdata, and was useless for users unless you hope to know how these built in data were prepared.

**Comment by korjcjeong** [comment]
Thank you for the quick reply, and I appreciate the script installing other required packages. 
I have installed all required packages since they are necessary during the TCGAplot installation.

However, I'm uncertain about the following instruction: 
"To install this package, download the TCGAplot R package at https://github.com/tjhwangxiong/TCGAplot/releases/download/v5.0.0/TCGAplot_5.0.0.zip DO NOT INSTALL USING 'devtools,' PLEASE download the .zip file and install the package locally."

As using ZIP is not an option for me on Mac, I followed these steps:

1. Download 'https://github.com/tjhwangxiong/TCGAplot/archive/refs/tags/v5.0.0.tar.gz'
2. Install the required packages
3. Run the following commands >>> install.packages('/my_local_path_to/TCGAplot-5.0.0.tar.gz', repo=NULL, type='source', dependencies=TRUE)
	Installing package into ‘/usr/local/lib/R/4.3/site-library’
	(as ‘lib’ is unspecified)
	* installing *binary* package ‘TCGAplot’ ...
	* DONE (TCGAplot)

I also unzip the 'zip' file and use the following commands to successfully install the package:
>>> install.packages('/my_local_path_to/TCGAplot/TCGAplot', repo=NULL, type='source', dependencies=TRUE)
	Installing package into ‘/usr/local/lib/R/4.3/site-library’
	(as ‘lib’ is unspecified)
	* installing *binary* package ‘TCGAplot’ ...
	* DONE (TCGAplot)


However, as you can see above, although the package was successfully installed, it still throws an error 'object 'tpm' not found.'

Again, thank you for your assistance.

**Comment by korjcjeong** [comment]
I have followed the revised instructions using the R-Studio interface for package installation, but it was unsuccessful. It appears that the current ZIP/tar.gz file is only compatible with Windows and is not functional on Mac.

**Comment by tjhwangxiong** [comment]
We provide the tar.gz file for Mac soon.

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："JC&nbsp;Jeong ***@***.***&gt;;
发送时间：2024年1月5日(星期五) 凌晨2:11
收件人："tjhwangxiong/TCGAplot" ***@***.***&gt;;
抄送："王雄 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [tjhwangxiong/TCGAplot] object 'tpm' not found (Issue #3)
-----------------------------------

 

 
I have followed the revised instructions using the R-Studio interface for package installation, but it was unsuccessful. It appears that the current ZIP/tar.gz file is only compatible with Windows and is not functional on Mac.

**Comment by korjcjeong** [comment]
The Mac version worked! 
This is a great tool, and thank you so much for your help!
