### ISSUE TITLE
Error in get_all_tpm() : could not find function "get_all_tpm"

### ISSUE THREAD

**Issue by Yanyouior** [tjhwangxiong/TCGAplot#4]
I tried to obtain the built-in data, but RStudio could not find function "get_all_xxxx". However, if I use the "get_xxxx ('xxxx')" function, I can obtain the relevant data. In addition, the help of the 'TCGAplot' version 5.0.0 package does not mention the 'get_all_xxxx()' function.

**Comment by tjhwangxiong** [comment]
We will release v7.0.0 ASAP


use v7.0.0

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Pan&nbsp;Zhang ***@***.***&gt;;
发送时间：2024年1月5日(星期五) 下午3:03
收件人："tjhwangxiong/TCGAplot" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[tjhwangxiong/TCGAplot] Error in get_all_tpm() : could not find function "get_all_tpm" (Issue #4)
-----------------------------------

 

 
I tried to obtain the built-in data, but RStudio could not find function "get_all_xxxx". However, if I use the "get_xxxx ('xxxx')" function, I can obtain the relevant data. In addition, the help of the 'TCGAplot' version 5.0.0 package does not mention the 'get_all_xxxx()' function.

**Comment by tjhwangxiong** [comment]
To install this package for Windows system, download TCGAplot R package at https://github.com/tjhwangxiong/TCGAplot/releases/download/v7.0.0/TCGAplot_7.0.0.zip

or at Baidu Pan
https://pan.baidu.com/s/1_zt-te0GmU_vbey3_Hx16Q?pwd=nmsy

and install locally.

install
To install this package for Mac system, download TCGAplot R package at google drive https://drive.google.com/file/d/1y79k-GQKz2b3Uv28eWDVYsCFPKVjm2WC/view?usp=sharing

or at Baidu Pan
https://pan.baidu.com/s/1a7-Z5N8C7YLSjTogMeXE_A?pwd=agf7

and install locally.
