### ISSUE TITLE
Trouble installing MacOS version of TCGAplot

### ISSUE THREAD

**Issue by Danfoltz** [tjhwangxiong/TCGAplot#5]
Congrats on the BMC article. It looks like a great tools I would like to use it but I am receiving the following error trying to install you TCGAplot.  
Error in install.packages : file ‘~/Downloads/mac_TCGAplot_7.0.0.tgz’ is not a macOS binary package

Any advice would be helpful. 
Thanks,
Dan

**Comment by tjhwangxiong** [comment]
I did not have macOS, and the mac_TCGAplot_7.0.0.tgz was built by a friend using mac M1.
