### ISSUE TITLE
lncRNA not found

### ISSUE THREAD

**Issue by HaotingJia1** [tjhwangxiong/TCGAplot#7]
Thanks for your great jobs!  i tried several lncRNA and they are not found. any way i can plot lncRNA data? thank you.

> > pan_boxplot('MALAT1')
> Error in `all_of()`:
> ! Can't subset columns that don't exist.
> ✖ Column `MALAT1` doesn't exist.

**Comment by tjhwangxiong** [comment]
Only coding genes were included.

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："HaotingJia1 ***@***.***&gt;;
发送时间：2024年1月18日(星期四) 凌晨4:15
收件人："tjhwangxiong/TCGAplot" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[tjhwangxiong/TCGAplot] lncRNA not found (Issue #7)
-----------------------------------

 

 
Thanks for your great jobs!  i tried several lncRNA and they are not found. any way i can plot lncRNA data? thank you.
   
pan_boxplot('MALAT1')
 Error in all_of():
 ! Can't subset columns that don't exist.
 ✖ Column MALAT1 doesn't exist.
