### ISSUE TITLE
> pan_boxplot("KLF7") Error in pan_boxplot("KLF7") : 找不到对象'tpm'

### ISSUE THREAD

**Issue by super-818** [tjhwangxiong/TCGAplot#8]
![image](https://github.com/tjhwangxiong/TCGAplot/assets/64523126/c60f456f-6049-41d9-ae98-604f5ae05880
![1706703559118](https://github.com/tjhwangxiong/TCGAplot/assets/64523126/8033db82-09e3-4ce9-9294-26b30c125dda)

**Comment by tjhwangxiong** [comment]
你TCGAplot没有被成功安装。

**Comment by super-818** [comment]
谢谢！



---原始邮件---
发件人: "Xiong ***@***.***&gt;
发送时间: 2024年2月1日(周四) 上午7:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tjhwangxiong/TCGAplot] &gt; pan_boxplot("KLF7") Error in pan_boxplot("KLF7") : 找不到对象'tpm' (Issue #8)




 
你TCGAplot没有被成功安装。

**Comment by super-818** [comment]
好像直接源码安装也不行哦，之前的版本已经卸载




梁沛宏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tjhwangxiong/TCGAplot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月1日(星期四) 上午7:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tjhwangxiong/TCGAplot] &gt; pan_boxplot("KLF7") Error in pan_boxplot("KLF7") : 找不到对象'tpm' (Issue #8)





 
你TCGAplot没有被成功安装。

**Comment by tjhwangxiong** [comment]
你把安装报错信息截图上来啊。不然我怎么知道什么错误。

**Comment by super-818** [comment]
在这，没报错




梁沛宏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tjhwangxiong/TCGAplot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月1日(星期四) 上午9:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tjhwangxiong/TCGAplot] &gt; pan_boxplot("KLF7") Error in pan_boxplot("KLF7") : 找不到对象'tpm' (Issue #8)





 
你把安装报错信息截图上来啊。不然我怎么知道什么错误。

**Comment by tjhwangxiong** [comment]
没看见你发的图

**Comment by tjhwangxiong** [comment]
请详细参考教程：https://github.com/tjhwangxiong/TCGAplot/blob/main/README.md
这里面已经说的非常详细具体了。

**Comment by super-818** [comment]
好的谢谢




梁沛宏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tjhwangxiong/TCGAplot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月1日(星期四) 上午9:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tjhwangxiong/TCGAplot] &gt; pan_boxplot("KLF7") Error in pan_boxplot("KLF7") : 找不到对象'tpm' (Issue #8)





 
请详细参考教程：https://github.com/tjhwangxiong/TCGAplot/blob/main/README.md
 这里面已经说的非常详细具体了。
